### ISSUE TITLE
Invalid prop `element` of type `boolean`

### ISSUE THREAD

**Issue by hsz** [Satyam/react-simple-idle-monitor#1]
In my isomorphic application, during the server rendering I get following error:

```
Warning: Failed prop type: Invalid prop `element` of type `boolean` supplied to `IdleMonitor`, expected `object`.
    in IdleMonitor (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by RouterContext)
    in RouterContext
    in Provider
```

I create idle monitor with:

```
<CustomIdleMonitor
  onActive={handleUpdateUserActivity}
  onIdle={handleSetUserIdle}
  timeout={15000}
>
  ...
</CustomIdleMonitor>
```

So default value of `element` property is used.

**Comment by Satyam** [comment]
@hsz Thanks for reporting the issue.  

The message is just a warning and it should not affect the final result. **Please, let me know if that is not so**.

I found it myself just after I published and fixed it in the source (https://github.com/Satyam/react-simple-idle-monitor/blob/master/src/index.jsx#L198 now it is of type `any` instead of `object` ) but being a warning, I delayed generating a new version. But if it is annoying (which it is), I'll publish a patch.

**Comment by hsz** [comment]
@Satyam That's correct - it's just a warning - component works even if it appears in the logs.

If you have a plan to make any release in the feature, we can wait with this patch until then. If not - I'd appreciate if you can push it as a new version. It's quite stressful when I see red colored messages in the logs. ;-)

Thanks!

**Comment by Satyam** [comment]
I have just published a new version with the corresponding patch.  The `PropType` for `element` is now `any` instead of `object` which should prevent it from complaining when there is no DOM.

I also added tests using the actual `renderToString` and `renderToStaticMarkup` just to make sure it works just as it does with Enzyme renderers.

**Comment by hsz** [comment]
That's a great news, thank you!
